### ISSUE TITLE
Cuadros a listas

### ISSUE THREAD

**Issue by eumati** [eumati/canastos#2]
Para mostrar la información existen dos estilos, el de mosaicos y el de lista, internamente en codigo, para mostrar uno u otro estilo, solo se debe de agregar la clase que determine el estilo de lista o mosaico, por ejemplo:
tengo mi contenedor: <div class="contenedor"></div>, si le agrego la clase tipo-mosaico, me lo mostrara como la imagen 1, si le agrego la clase tipo-lista, me mostrara como la imagen 2, el codigo javascript para agregar o quitar cualquiera de las dos clases mencionadas anteriormente lo hara otra persona.

![image](https://cloud.githubusercontent.com/assets/8921806/18922417/29c3a802-856e-11e6-84f5-afbcc8552f79.png)

![image](https://cloud.githubusercontent.com/assets/8921806/18922422/315abc40-856e-11e6-9672-508f8ce71678.png)

**Comment by MoarDante** [comment]
div.Producto: Cambiar .small-4 por .small-12
div.fotoProducto: Agregar .columns y .small-4
div.contenidoProducto: Agregar .columns y .small-8
div.hoverProducto y div.controlesProducto: Agregar .is-hidden
div.nombreProducto: Cambiar .small-6 por .small-5
div.precioProducto: Cambiar .small-6 por .small-4
div.descripcionList: Quitar .is-hidden
div.contIconos: Quitar .is-hidden
